# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Rx
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'

  # UIKit
  pod 'SnapKit'
  pod 'Then'
  
  # UI Related Pods
  pod 'Cosmos'

  # Code Convention
  pod 'SwiftLint'

end
